<Project>
    <PropertyGroup>
        <CompatibilityTargetFrameworks>netstandard2.0</CompatibilityTargetFrameworks>
        <DefaultTargetFramework>net9.0</DefaultTargetFramework>
        <UseLocalProjects Condition="'$(UseLocalProjects)' == ''">true</UseLocalProjects>
    </PropertyGroup>
    
    <ItemGroup>
        <ProjectReference Include="..\..\..\aevatar-station\framework\src\Aevatar.Core.Abstractions\Aevatar.Core.Abstractions.csproj" />
    </ItemGroup>
</Project>